Kong/kong-vagrant

Vagrantfile

This adds git to 'precise64' box. 
I've noticed the my other PR #3 will require vagrant 1.5+.
so i added this, as a more 'consevative' update.
it adds git and curl, i know curl is not required but it is really helpful to have.

added 'git' and 'curl' to precise64 box (issue #2)

---

Vagrantfile

adds the ability to control machine RAM size without update Vagrant file.
for example:
start vm with 4G RAM
<pre>
KONG_PATH=/path/to/kong KONG_VB_MEM=4096 vagrant up
</pre>
if one does not set the 'KONG_VB_MEM' env var the default is 2048, as its today.
<pre>
KONG_PATH=/path/to/kong vagrant up
</pre>

add env var to control machine RAM (issue #6)

---

README.md
Vagrantfile
provision.sh

- fix startup issues
- set minimum required Vagrant version at `1.4.3`
- use `wget` instead of `curl` (unavailable at the time) for grabbing datastax repo key
- default value for soruce folder, prevents errors on calling `vagrant` without environment variable
- use downloadkong.org to grab the latest released version automatically
- fix unknown $OUT variable
- switch to Oracle Java 8 as recommended by Datastax
- download and install Oracle Java 8.6_60

improvements + Oracle Java 8

---

Vagrantfile
provision.sh

Some plugins tests needs redis to be installed, with the right permissions on /var/log/redis/redis-server.log
```
#ci Plugin: rate-limiting (access) with policy: local setup
spec/03-plugins/98-rate-limiting/04-access_spec.lua:28: bad argument #2 to 'error' (number expected, ot string)
stack traceback:
spec/03-plugins/98-rate-limiting/04-access_spec.lua:28: in function 'flush_redis'
spec/03-plugins/98-rate-limiting/04-access_spec.lua:46: in function <spec/03-plugins/98-rate-limiting/04-access_spec.lua:44>
Failure → spec/03-plugins/005-syslog/01-log_spec.lua @ 99
#ci Plugin: syslog (log) logs to syslog if log_level is lower
spec/03-plugins/005-syslog/01-log_spec.lua:94: grep: /var/log/redis/redis-server.log: Permission denied
stack traceback:
./kong/core/globalpatches.lua:158: in function …
```

Some plugins tests needs redis to be installed

---

README.md
Vagrantfile
provision.sh

Upon provisioning creates a script `~/cassandra2.sh` that will install Cassandra 2.x in the vagrant box.
This will ease the test setup for new (plugin) developers. 
Steps:
```
~/cassandra2.sh
cd /kong
make dev
make test-all
```

Add Cassandra installation option

---

.gitignore
README.md
Vagrantfile
provision.sh

The source repos are now completely optional, such that the Vagrant box can also be used as an all-in-1 test box, to quickly try Kong.
Cassandra 3.x is now default for 0.10 release, 2.x remains for 0.9 and below. With a setting to force a  version.
added default repo locations inside the vagrant repo. So its a cleaner throw-away install for basic testing.

Optional repos, and cassandra 3

---

README.md

* trim trailing white spaces
* fix a couple of typos
* proper capitalization of standardized names and acronyms, or proper
names
* Oxford comma
* https:// links in favor of plain HTTP when possible

docs(readme) cleanup + capitalization

---

README.md

Current documentation ends up with a text paragraph stuck in a code block.

Adding a missing closing block quote

---

provision.sh

new tests rely on calling the openresty nginx binary directly via
shell.

add openresty nginx sbin to PATH

---

README.md
Vagrantfile

Provide a default for vb.cpus that enables Kong to start with multiple
workers. This more closely mimics a Kong node running in production
and increases the chances for developers to discover concurrency bugs
before issuing a PR.
Default is set to two under the assumption that most developers have
a multi-cpu machine these days. VirtualBox will silently start with
a value of one, effectively reverting to the behavior we have today.
Tested on Mac only.

feat(box-config) default to two workers

---

README.md
Vagrantfile
provision.sh

Copies host setting for cpus/processes, log level, and auto sets the prefix.
1. removes `KONG_VB_CPUS` optional environment variable, instead it uses the standard kong one called `KONG_NGINX_WORKER_PROCESSES` which is slightly different but solved the exact same problem. Provisioning will now use the `KONG_NGINX_WORKER_PROCESSES` variable, or otherwise the default of `2` to set the number of cpus.
1. the `KONG_LOG_LEVEL` variable will be copied from the host into the vm when provisioning.
1. the `KONG_PREFIX` in the vm will be set to `/kong/servroot`, which means it will be accessible from the host system where it is located at `<Kong repo>/servroot`, the same location where the tests run.
The idea of this change is to make it easier to rebuild the vagrant box, by specifying the settings …

copy host setting into vm

---

README.md
provision.sh

Kong 0.12 switched to listen on localhost only by default. This
prevents the access to the admin api from the host machine.
We override it by listening on all interfaces again.

fix(provision) make admin listen on all interfaces

---

provision.sh

Following the instructions to set up a development environment eventually leads to this error:
```sh
vagrant@ubuntu-xenial:/kong$ make dev
Checking stability of dependencies in the absence of
kong 0.14.0-0...
Removing kong 0.14.0-0...
Removal successful.
Missing dependencies for kong 0.14.0-0:
luaossl == 20180708 (20171028-0 installed)
kong 0.14.0-0 depends on luaossl == 20180708 (20171028-0 installed)
Installing https://luarocks.org/luaossl-20180708-0.src.rock
Error: Failed installing dependency: https://luarocks.org/luaossl-20180708-0.src.rock - Could not find header file for CRYPTO
No file openssl/crypto.h in /usr/include
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_INCDIR to the luarocks command.
Example: luarocks install luaossl CRYPTO_DIR=/usr/local …
```

add libssl-dev to APT packages list

---

provision.sh

This auto-starts postgresql on image boot. Right now when the
image is brought down and back up, the DB does not automatically start
on subsequent boots.

Enable postgresql service

---

provision.sh

This enforces that the mounted Kong source path is used first
in the Lua path search

Add /kong into LUA_PATH

---

README.md
Vagrantfile

Bumps Kong from `1.0.0` to `1.0.1`.
PS. if you approve, please merge right away, and delete the branch.

chore(*) bump Kong version to 1.0.1

---

README.md

docs(conf) fix
When execute the command 'make dev' for setup the dev environment and error occurs when install luasec dependencies.
And the export environment variable for custom plugins its change.(KONG_CUSTOM_PLUGINS -> KONG_PLUGINS).
That error produced a blocking for setup the environment for develop a custom plugin.

Error in steps for enviroments in README docs

---

provision.sh

Bump SystemTap version to 4.0. `gcc` version in Ubuntu 18.04 base includes some new warnings by default, which breaks the compilation of SystemTap 3.0, unless we manually disable particular compiler checks - e.g., `-Wimplicit-fallthrough=0` - by hand. SystemTap 4.0 fixed the issues making the compiler unhappy. If there are concerns with bumping to 4.0, we can go the compiler flags tuning route.

chore(utilities) bump systemtap version to 4.0

---

README.md
Vagrantfile
provision.sh

- Updated Kong version to 1.2.0.
- Removed oracle-java8-installer from provision.sh as it is not available after licensing changes.

chore(*) bump Kong to 1.2.0

---

provision.sh

Fix Kong package download URL in a backward-compatible way. Given arm64 was only introduced with 1.3.0, only packages for Kong versions >= 1.3.0 have the new URL.

fix(provision) kong package url

---

provision.sh

This prints a warning when the source tree does not match the version build in the box (eg. it doesn't match the binary components installed in the box)
closes #141

feat(warn) warn when versions do not match

---

.travis.yml
Vagrantfile

this does not successfully run Kong
Example failure here: https://travis-ci.com/github/Kong/kong-vagrant/builds/180702282#L1305
But it does run `vagrant validate` and `vagrant up` which will include the provision script therefore I think this has value

chore(ci) add travis-ci tests

---

.travis.yml

must have missed this in the previous PR

chore(ci) run kong version to validate our Kong installation in vagrant

---

README.md

I followed the README.md instructions for setting up a service this morning, and encountered an error when I tried to add a route to the mockbin service:
```bash
$ curl -i -X POST \
>   --url http://localhost:8001/services/mockbin/routes \
>   --data 'paths=/'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   170  100   143  100    27     89     16  0:00:01  0:00:01 --:--:--   106HTTP/1.1 400 Bad Request
Date: Tue, 15 Sep 2020 23:41:55 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/2.1.3
Content-Length: 143
X-Kong-Admin-Latency: 1371
{"message":"schema violation (paths.1: should start with: \/)","name":"schema …
```

Fix example curl command in README.md

---

.travis.yml
README.md
Vagrantfile

This PR bumps Kong to the latest version and also fixes a problem with Vagrant 2.2.8 on the CI (Nokogiri, one of the dependencies, [failed to install](https://github.com/mitchellh/vagrant-google/issues/238)) so I have bumped the Vagrant version used in CI to 2.2.9, which fixed the issue.

chore(*) bump Kong to 2.3.0

---

Vagrantfile
provision.sh

Currently in use base image is for Ubuntu 16.04 - which is currently in Extended Security maintenance. This PR updates the base to Ubuntu 20.04, the latest LTS release.

chore(vagrant) bump ubuntu to focal
